### PR TITLE
HeapSort and SelectionSort

### PR DESCRIPTION
**Pull request by ruhirani011**
Created HeapSort.cpp and SelectionSort.cpp 
@recongamer Please review and accept.

### CODE REVIEW

**Review by recongamer — COMMENTED** [review]
Dear Ruhi, I can't approve your pull request  and merge the code in this repository as the code for this is already available in this repo. I recommend you to solve another problem and then submit the PR . However It was great to see someone from BIT Sindri and conntributing to a month long hacktoberfest 2021. I'm also from Jharkhand(Daltonganj), currently pursuing B.Tech in IT from Indian Institute of Information Technology Allahabad. My best wishes to you for your future endeavours.

**Comment by ruhirani011** [comment]
Thanks for your kind wishes @recongamer  sir
I have removed Bubble Sort . But can you please tell that Is heap sort and selection sort are present in this repo or not . I didn't found it here.
If it's not present then please accept.

**Comment by recongamer** [comment]
I'm merging  your code since it's not in this repository. However , I encourage you to submit more PRs. If you need any help you can connect with me on facebook. Here's the link https://www.facebook.com/raushaniiita/

**Comment by ruhirani011** [comment]
> However , I encourage you to submit more PRs. 

Sure sir 😊

**Comment by recongamer** [comment]
I see you are active in open source, You cam have a look at  GirlScript Summer of Code internship program (since it's only for girls so there will be less competition. ) You can even try for GSoc(Google Summer of Code). 
However,if you want to get placed in product based company through off campus or any referral , then get your hands dirty in competitive programming learn and explore DSA.

**Pull request merged**
