### PR TITLE
Create TripletSum.cpp

### PR DESCRIPTION
**Pull request by khushi-0001**

### CODE REVIEW

**Comment by khushi-0001** [comment]
Okay , doing it right now

**Comment by recongamer** [comment]
Btw where are you from ?

**Comment by khushi-0001** [comment]
From panipat, Haryana

**Comment by raushanraj358** [comment]
Can we connect on Instagram or Facebook?

**Comment by recongamer** [comment]
@khushi-0001 I'm originally from Daltonganj, Jharkhand. But I've been in Allahabad for the last 3 years, where i'm pursuing B.Tech in IT from Indian Institute of Information Technology Allahabad.

Insta - raushanspeaks

**Comment by khushi-0001** [comment]
Okay great

**Pull request merged**
